---
name: 'Checks for unique name, id and social link'
'on':
  push:
    branches:
      - kratika
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@kratika
      - name: check perform
        uses: ./scripts/checks.js
        with:
          node-version: 10.x