
name: 'Checks for unique name, id and social link'
'on':
  push:
    branches:
      - kratika
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps :
      - name: Checkout
        uses: actions/checkout@kratika
      - name: run file 
        uses: ./
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}